'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace WebDevelopmentProjectWebService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebDevelopmentProjectWebServiceSoap", [Namespace]:="http://tempuri.org/WebDevelopmentProjectWS/WebDevelopmentProjectWebService")>  _
    Public Class WebDevelopmentProjectWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("WebDeploymentProject.WebDevelopmentProjectWebService.WebDevelopmentProjectWebServ"& _ 
"ice")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/WebDevelopmentProjectWS/WebDevelopmentProjectWebService.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebDevelopmentProjectWS/WebDevelopmentProjectWebService/GetIni"& _ 
"tTime", RequestNamespace:="http://tempuri.org/WebDevelopmentProjectWS/WebDevelopmentProjectWebService", ResponseNamespace:="http://tempuri.org/WebDevelopmentProjectWS/WebDevelopmentProjectWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInitTime() As Date
            Dim results() As Object = Me.Invoke("GetInitTime", New Object(-1) {})
            Return CType(results(0),Date)
        End Function
        
        '<remarks/>
        Public Function BeginGetInitTime(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetInitTime", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetInitTime(ByVal asyncResult As System.IAsyncResult) As Date
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Date)
        End Function
    End Class
End Namespace
